format = """
[](#a277ff)\
$os\
$username\
[](bg:#61ffca fg:#a277ff)\
$directory\
[](bg:#ffca85 fg:#61ffca)\
$git_branch\
$git_status\
[](bg:#f694ff fg:#ffca85)\
$bun\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](bg:#82e2ff fg:#f694ff)\
$docker_context\
[](bg:#edecee fg:#82e2ff)\
$time\
[ ](fg:#edecee)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#a277ff fg:#edecee"
style_root = "bg:#a277ff fg:#edecee"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#a277ff"
disabled = true # Disabled by default

[directory]
style = "bg:#61ffca fg:#15141b"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[bun]
symbol = ""
style = "bg:#f694ff fg:#15141b"
format = '[ $symbol ($version) ]($style)'

[c]
symbol = ""
style = "bg:#f694ff fg:#15141b"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = ""
style = "bg:#f694ff fg:#15141b"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = ""
style = "bg:#82e2ff fg:#15141b"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = ""
style = "bg:#f694ff fg:#15141b"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = ""
style = "bg:#f694ff fg:#15141b"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#ffca85 fg:#15141b"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#ffca85 fg:#15141b"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = ""
style = "bg:#f694ff fg:#15141b"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#f694ff fg:#15141b"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = ""
style = "bg:#f694ff fg:#15141b"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = ""
style = "bg:#f694ff fg:#15141b"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = ""
style = "bg:#f694ff fg:#15141b"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#f694ff fg:#15141b"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = ""
style = "bg:#f694ff fg:#15141b"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#f694ff fg:#15141b"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = ""
style = "bg:#f694ff fg:#15141b"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#edecee fg:#15141b"
format = '[ 󱑆 $time ]($style)'
